### ISSUE TITLE
Feature Request: Forbidden Pairings

### ISSUE THREAD

**Issue by mauserk98grenaderifle** [Moritz72/ToMaChess#2]
You can add options for Forbidden Pairings, where in Swiss tournament or round robin, players can be tagged so that the players will not compete.

**Comment by Moritz72** [comment]
I'll have to think a bit about how to design the graphical interface for choosing the forbidden pairings, because I think none of the currently used ones would work well.
Once I have that it should be pretty easy to do this for Swiss tournaments, since the pairing engine I use (bbpPairings) already supports forbidden pairings. But for Round Robin tournaments I don't see how forbidden pairings would make sense.

**Comment by Moritz72** [comment]
I added it now as an "Action". So when you open a tournament and click on "Actions" at the bottom of the sidebar, you can click on "Forbidden Pairings" to add forbidden pairings. But this "Action" is only available for Swiss tournaments and it will not work for non-standard methods in the first round (only for "Slide" not for "Fold", "Random" or "Custom").
I'll probably make a new release next week, but I have to first make sure that everything still works and I didn't introduce some bug.

**Comment by mauserk98grenaderifle** [comment]
Thanks, your work is appreciated.
